/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asm;

import dao.ProveedorDao;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import modelo.Proveedor;

/**
 *
 * @author leopa
 */
public class FrmDatosProveedor extends javax.swing.JFrame {

    ProveedorDao proveedorDao;
    private final String id;
    private final FrmProveedores proveedores;
    private String accion;
    public FrmDatosProveedor(Proveedor proveedor,FrmProveedores proveedores) {
         proveedorDao = new ProveedorDao();
        initComponents();
        if(proveedor != null){
            boolean[] dias = proveedor.getDias();
            id = proveedor.getId();
            txtNombre.setText(proveedor.getNombre());
            txtTelefono.setText(proveedor.getTelefono());
            txtCorreo.setText(proveedor.getCorreo());
            tboxLunes.setSelected(dias[0]);
            tboxMartes.setSelected(dias[1]);
            tboxMiercoles.setSelected(dias[2]);
            tboxJueves.setSelected(dias[3]);
            tboxViernes.setSelected(dias[4]);
            tboxSabado.setSelected(dias[5]);
            tboxDomingo.setSelected(dias[6]);
            accion = "actualizado";
        }else{
           int ultimoRegistro = DevolverUltimoID();
           id = "Pr_"+(ultimoRegistro+1);  
           accion = "agregado";
        }
       
        this.proveedores = proveedores; 
       
        
        lblId.setText("ID proveedor " + id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblLunes = new javax.swing.JLabel();
        lblMartes = new javax.swing.JLabel();
        lblMiercoles = new javax.swing.JLabel();
        lblJueves = new javax.swing.JLabel();
        lblViernes = new javax.swing.JLabel();
        lblSabado = new javax.swing.JLabel();
        lblDomingo = new javax.swing.JLabel();
        tboxLunes = new javax.swing.JCheckBox();
        tboxMartes = new javax.swing.JCheckBox();
        tboxMiercoles = new javax.swing.JCheckBox();
        tboxJueves = new javax.swing.JCheckBox();
        tboxViernes = new javax.swing.JCheckBox();
        tboxSabado = new javax.swing.JCheckBox();
        tboxDomingo = new javax.swing.JCheckBox();
        lblDiasReparto = new javax.swing.JLabel();
        btnAgregarActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Datos proveedor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblId.setText("Id proveedor:");

        lblNombre.setText("Nombre del proveedor: ");

        lblTelefono.setText("Telefono:");

        lblCorreo.setText("Correo:");

        lblLunes.setText("LUN");

        lblMartes.setText("MAR");

        lblMiercoles.setText("MIE");

        lblJueves.setText("JUE");

        lblViernes.setText("VIE");

        lblSabado.setText("SAB");

        lblDomingo.setText("DOM");

        tboxLunes.setAutoscrolls(true);
        tboxLunes.setBorder(null);

        tboxMartes.setBorder(null);
        tboxMartes.setBorderPainted(true);

        tboxMiercoles.setBorder(null);

        tboxJueves.setBorder(null);

        tboxViernes.setBorder(null);

        tboxSabado.setBorder(null);

        tboxDomingo.setBorder(null);

        lblDiasReparto.setText("Dias de reparto:");

        btnAgregarActualizar.setAutoscrolls(true);
        btnAgregarActualizar.setBorder(null);
        btnAgregarActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarActualizar.setLabel("Aceptar");
        btnAgregarActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarActualizarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setAutoscrolls(true);
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblTelefono)
                                    .addComponent(lblCorreo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgregarActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLunes)
                                    .addComponent(tboxLunes))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMartes)
                                    .addComponent(tboxMartes))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tboxMiercoles)
                                    .addComponent(lblMiercoles))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tboxJueves)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblJueves)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblViernes)
                                    .addComponent(tboxViernes))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSabado)
                                    .addComponent(tboxSabado))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tboxDomingo)
                                    .addComponent(lblDomingo)))
                            .addComponent(lblDiasReparto))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblId)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDiasReparto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLunes)
                    .addComponent(lblMartes)
                    .addComponent(lblMiercoles)
                    .addComponent(lblJueves)
                    .addComponent(lblViernes)
                    .addComponent(lblSabado)
                    .addComponent(lblDomingo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tboxLunes)
                    .addComponent(tboxMartes)
                    .addComponent(tboxMiercoles)
                    .addComponent(tboxJueves)
                    .addComponent(tboxViernes)
                    .addComponent(tboxSabado)
                    .addComponent(tboxDomingo))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private int DevolverUltimoID(){
        int id = 0;
        String[] partesId;
        Proveedor proveedor = proveedorDao.buscarUltimoProveedor();
        if(proveedor != null){
            partesId = proveedor.getId().split("_");
            id = Integer.parseInt(partesId[1]);
            System.out.println(id);
        }
        return id;
    }
    private void btnAgregarActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarActualizarMouseClicked
        JCheckBox[] diasReparto = {tboxLunes,tboxMartes,tboxMiercoles,tboxJueves,tboxViernes,tboxSabado,tboxDomingo};
        int diasElegidos = 0;
        boolean correoValido = true;
        boolean[] dias = new boolean[7];
        for(int i = 0; i < 7; i++){
            dias[i] = diasReparto[i].isSelected();
            if(diasReparto[i].isSelected())
                diasElegidos ++;
        }
        if(!txtCorreo.getText().isEmpty())
            correoValido = Proveedor.correoValido(txtCorreo.getText());
       if(!txtNombre.getText().isEmpty() && !txtTelefono.getText().isEmpty() && diasElegidos > 0){
          Proveedor proveedor = new Proveedor(id,txtNombre.getText(),txtTelefono.getText(),txtCorreo.getText(),dias);
          if(Proveedor.telefonoValido(proveedor.getTelefono()) && correoValido){
              if(accion.equals("agregado"))
                proveedorDao.insertar(proveedor);
              else
                proveedorDao.actualizarProveedor(proveedor);
              
              formWindowClosed(null);
              
              JOptionPane.showMessageDialog(null,"Proveedor "+accion+" con exito","En hora buena", JOptionPane.INFORMATION_MESSAGE);
          }else
             JOptionPane.showMessageDialog(null,"Numero de telefono o correo invalido, favor de revisar","Invalido", JOptionPane.ERROR_MESSAGE); 
          
       }else
           JOptionPane.showMessageDialog(null,"Datos necesarios incompletos, favor de revisar","Incompleto", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnAgregarActualizarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        proveedores.limpiarTabla();
        proveedores.lista = proveedorDao.pedirTabla();
        proveedores.llenarTabla(proveedores.lista);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed
    
   
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDatosProveedor(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDiasReparto;
    private javax.swing.JLabel lblDomingo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJueves;
    private javax.swing.JLabel lblLunes;
    private javax.swing.JLabel lblMartes;
    private javax.swing.JLabel lblMiercoles;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSabado;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblViernes;
    private javax.swing.JCheckBox tboxDomingo;
    private javax.swing.JCheckBox tboxJueves;
    private javax.swing.JCheckBox tboxLunes;
    private javax.swing.JCheckBox tboxMartes;
    private javax.swing.JCheckBox tboxMiercoles;
    private javax.swing.JCheckBox tboxSabado;
    private javax.swing.JCheckBox tboxViernes;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
